require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/emission_contents", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EmissionContent. As you add validations to EmissionContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EmissionContent.create! valid_attributes
      get emission_contents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      emission_content = EmissionContent.create! valid_attributes
      get emission_content_url(emission_content)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_emission_content_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      emission_content = EmissionContent.create! valid_attributes
      get edit_emission_content_url(emission_content)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EmissionContent" do
        expect {
          post emission_contents_url, params: { emission_content: valid_attributes }
        }.to change(EmissionContent, :count).by(1)
      end

      it "redirects to the created emission_content" do
        post emission_contents_url, params: { emission_content: valid_attributes }
        expect(response).to redirect_to(emission_content_url(EmissionContent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EmissionContent" do
        expect {
          post emission_contents_url, params: { emission_content: invalid_attributes }
        }.to change(EmissionContent, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post emission_contents_url, params: { emission_content: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested emission_content" do
        emission_content = EmissionContent.create! valid_attributes
        patch emission_content_url(emission_content), params: { emission_content: new_attributes }
        emission_content.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the emission_content" do
        emission_content = EmissionContent.create! valid_attributes
        patch emission_content_url(emission_content), params: { emission_content: new_attributes }
        emission_content.reload
        expect(response).to redirect_to(emission_content_url(emission_content))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        emission_content = EmissionContent.create! valid_attributes
        patch emission_content_url(emission_content), params: { emission_content: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested emission_content" do
      emission_content = EmissionContent.create! valid_attributes
      expect {
        delete emission_content_url(emission_content)
      }.to change(EmissionContent, :count).by(-1)
    end

    it "redirects to the emission_contents list" do
      emission_content = EmissionContent.create! valid_attributes
      delete emission_content_url(emission_content)
      expect(response).to redirect_to(emission_contents_url)
    end
  end
end
