require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/reportages', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Reportage. As you add validations to Reportage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Reportage.create! valid_attributes
      get reportages_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      reportage = Reportage.create! valid_attributes
      get reportage_url(reportage)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_reportage_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      reportage = Reportage.create! valid_attributes
      get edit_reportage_url(reportage)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Reportage' do
        expect do
          post reportages_url, params: { reportage: valid_attributes }
        end.to change(Reportage, :count).by(1)
      end

      it 'redirects to the created reportage' do
        post reportages_url, params: { reportage: valid_attributes }
        expect(response).to redirect_to(reportage_url(Reportage.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Reportage' do
        expect do
          post reportages_url, params: { reportage: invalid_attributes }
        end.to change(Reportage, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post reportages_url, params: { reportage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested reportage' do
        reportage = Reportage.create! valid_attributes
        patch reportage_url(reportage), params: { reportage: new_attributes }
        reportage.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the reportage' do
        reportage = Reportage.create! valid_attributes
        patch reportage_url(reportage), params: { reportage: new_attributes }
        reportage.reload
        expect(response).to redirect_to(reportage_url(reportage))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        reportage = Reportage.create! valid_attributes
        patch reportage_url(reportage), params: { reportage: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested reportage' do
      reportage = Reportage.create! valid_attributes
      expect do
        delete reportage_url(reportage)
      end.to change(Reportage, :count).by(-1)
    end

    it 'redirects to the reportages list' do
      reportage = Reportage.create! valid_attributes
      delete reportage_url(reportage)
      expect(response).to redirect_to(reportages_url)
    end
  end
end
